---
- name: copy selinux config
  copy: src=selinux dest=/etc/sysconfig/selinux

- name: set selinux disabled
  shell: setenforce 0
  ignore_errors: True

- name: copy the centos docker file
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: 'centos_docker/docker-engine-selinux-1.12.6-1.el7.centos.noarch.rpm', dest: '/tmp/docker-engine-selinux-1.12.6-1.el7.centos.noarch.rpm'}
    - {src: 'centos_docker/docker-engine-1.12.6-1.el7.centos.x86_64.rpm', dest: '/tmp/docker-engine-1.12.6-1.el7.centos.x86_64.rpm'}

- name: install docker 1.12
  shell: cd /tmp && yum install -y docker-engine-selinux-1.12.6-1.el7.centos.noarch.rpm && yum install -y docker-engine-1.12.6-1.el7.centos.x86_64.rpm
  tags:
    - installs

- name: start docker service
  service: name=docker state=started
  tags:
    - starts

- name: copy ali centos7 sources
  copy: src=epel-release-latest-7.noarch.rpm dest=/tmp/epel-release-latest-7.noarch.rpm

- name: exec centos7 sources
  shell: rpm -ivh /tmp/epel-release-latest-7.noarch.rpm

- name: install python-pip
  yum: name=python-pip state=present force=yes

- name: install docker-py
  pip:
    name: docker-py
