---
- name: copy zabbix_agent docker images
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: 'zabbix_agent_images/zabbix_agent_ubuntu_3.0.9.tar', dest: '/tmp/zabbix_agent_ubuntu_3.0.9.tar'}

- name: docker import zabbix_agent images
  shell: docker load -i {{ item }}
  with_items:
    - /tmp/zabbix_agent_ubuntu_3.0.9.tar

- name: create zabbix_agent_conf directory
  file: path={{ zbx_agent_path }} state=directory mode=755

- name: copy zabbix_agent config,这里一定要复制个zabbix_agentd.conf，否则会找不到文件，不用设置变量会被覆盖
  template: src=zabbix_agentd.conf dest={{ zbx_agent_path }}/zabbix_agentd.conf

- name: create zabbix-agent docker container
  docker_container:
    name: "{{ zbx_agent_dockername }}"
    image: zabbix/zabbix-agent:ubuntu-3.0.9
    detach: True
    ports:
      - "10050:10050"
    env:
      ZBX_SERVER_HOST: "{{ zbx_server_host }}"
      ZBX_HOSTNAME: "{{ ansible_default_ipv4.address }}"
      ZBX_SERVER_PORT: 10051
    volumes:
      - "{{ zbx_agent_path }}:/etc/zabbix:rw"
  tags:
    - docker5
