---
- name: create zabbix_agent_conf directory
  file: path={{ /opt/zabbix_agent_conf }} state=directory mode=755

- name: copy zabbix_agent config
  template: src=zabbix_agentd.conf dest={{ /opt/zabbix_agent_conf }}/zabbix_agentd.conf

- name: create zabbix-agent docker container
  docker_container:
    name: {{ zabbix_server_dockername }}
    image: zabbix/zabbix-agent:ubuntu-3.0.9
    detach: True
    ports:
      - "10050:10050"
    env:
      ZBX_SERVER_HOST: {{ zabbix_server_host }}
      ZBX_SERVER_PORT: 10051
    volumes:
      - {{ /opt/zabbix_agent_conf }}:/etc/zabbix:rw

